name: Build Fyne Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23' # 设置你需要的 Go 版本

    - name: Install Fyne
      run: go get fyne.io/fyne/v2

    - name: Build the project
      run: go build -o myapp ./cmd/myapp

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: myapp
        path: myapp

