name: Build Fyne Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23' # 设置你需要的 Go 版本

    - name: Install Fyne
      run: go get fyne.io/fyne/v2
      
    - name: Install goja
      run: go get  github.com/dop251/goja
      
    - name: Install colly
      run: go get github.com/gocolly/colly/v2

    - name: Build the project
      run: go build -o myapp ./myapp

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
          name: my-artifact
          path: path/to/artifact





