name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17'

    - name: Install dependencies
      run: |
        go get -v github.com/fyne-io/fyne/v2
        go get -v github.com/dop251/goja
        go get -v github.com/gocolly/colly/v2

    - name: Build the project
      run: go build -o myapp.exe .

    - name: Run tests
      run: go test -v ./...

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.token }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v2
      env:
        GITHUB_TOKEN: ${{ secrets.token }}
      with:
        # upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./myapp.exe
        asset_name: myapp.exe
        asset_content_type: application/octet-stream
